// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: internal/proto/handlers.proto

package protobuf

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserHandlers_PostUserData_FullMethodName = "/server_grpc.UserHandlers/PostUserData"
)

// UserHandlersClient is the client API for UserHandlers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserHandlersClient interface {
	PostUserData(ctx context.Context, in *PostUserDataRequest, opts ...grpc.CallOption) (*PostUserDataResponse, error)
}

type userHandlersClient struct {
	cc grpc.ClientConnInterface
}

func NewUserHandlersClient(cc grpc.ClientConnInterface) UserHandlersClient {
	return &userHandlersClient{cc}
}

func (c *userHandlersClient) PostUserData(ctx context.Context, in *PostUserDataRequest, opts ...grpc.CallOption) (*PostUserDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostUserDataResponse)
	err := c.cc.Invoke(ctx, UserHandlers_PostUserData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserHandlersServer is the server API for UserHandlers service.
// All implementations must embed UnimplementedUserHandlersServer
// for forward compatibility.
type UserHandlersServer interface {
	PostUserData(context.Context, *PostUserDataRequest) (*PostUserDataResponse, error)
	mustEmbedUnimplementedUserHandlersServer()
}

// UnimplementedUserHandlersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserHandlersServer struct{}

func (UnimplementedUserHandlersServer) PostUserData(context.Context, *PostUserDataRequest) (*PostUserDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostUserData not implemented")
}
func (UnimplementedUserHandlersServer) mustEmbedUnimplementedUserHandlersServer() {}
func (UnimplementedUserHandlersServer) testEmbeddedByValue()                      {}

// UnsafeUserHandlersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserHandlersServer will
// result in compilation errors.
type UnsafeUserHandlersServer interface {
	mustEmbedUnimplementedUserHandlersServer()
}

func RegisterUserHandlersServer(s grpc.ServiceRegistrar, srv UserHandlersServer) {
	// If the following call pancis, it indicates UnimplementedUserHandlersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserHandlers_ServiceDesc, srv)
}

func _UserHandlers_PostUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostUserDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserHandlersServer).PostUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserHandlers_PostUserData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserHandlersServer).PostUserData(ctx, req.(*PostUserDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserHandlers_ServiceDesc is the grpc.ServiceDesc for UserHandlers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserHandlers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server_grpc.UserHandlers",
	HandlerType: (*UserHandlersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostUserData",
			Handler:    _UserHandlers_PostUserData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/handlers.proto",
}

const (
	ItemDataHandlers_PostItemData_FullMethodName = "/server_grpc.ItemDataHandlers/PostItemData"
	ItemDataHandlers_GetItemData_FullMethodName  = "/server_grpc.ItemDataHandlers/GetItemData"
)

// ItemDataHandlersClient is the client API for ItemDataHandlers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ItemDataHandlersClient interface {
	PostItemData(ctx context.Context, in *PostItemDataRequest, opts ...grpc.CallOption) (*PostItemDataResponse, error)
	GetItemData(ctx context.Context, in *GetItemDataRequest, opts ...grpc.CallOption) (*GetItemDataResponse, error)
}

type itemDataHandlersClient struct {
	cc grpc.ClientConnInterface
}

func NewItemDataHandlersClient(cc grpc.ClientConnInterface) ItemDataHandlersClient {
	return &itemDataHandlersClient{cc}
}

func (c *itemDataHandlersClient) PostItemData(ctx context.Context, in *PostItemDataRequest, opts ...grpc.CallOption) (*PostItemDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostItemDataResponse)
	err := c.cc.Invoke(ctx, ItemDataHandlers_PostItemData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemDataHandlersClient) GetItemData(ctx context.Context, in *GetItemDataRequest, opts ...grpc.CallOption) (*GetItemDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemDataResponse)
	err := c.cc.Invoke(ctx, ItemDataHandlers_GetItemData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemDataHandlersServer is the server API for ItemDataHandlers service.
// All implementations must embed UnimplementedItemDataHandlersServer
// for forward compatibility.
type ItemDataHandlersServer interface {
	PostItemData(context.Context, *PostItemDataRequest) (*PostItemDataResponse, error)
	GetItemData(context.Context, *GetItemDataRequest) (*GetItemDataResponse, error)
	mustEmbedUnimplementedItemDataHandlersServer()
}

// UnimplementedItemDataHandlersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedItemDataHandlersServer struct{}

func (UnimplementedItemDataHandlersServer) PostItemData(context.Context, *PostItemDataRequest) (*PostItemDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostItemData not implemented")
}
func (UnimplementedItemDataHandlersServer) GetItemData(context.Context, *GetItemDataRequest) (*GetItemDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemData not implemented")
}
func (UnimplementedItemDataHandlersServer) mustEmbedUnimplementedItemDataHandlersServer() {}
func (UnimplementedItemDataHandlersServer) testEmbeddedByValue()                          {}

// UnsafeItemDataHandlersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ItemDataHandlersServer will
// result in compilation errors.
type UnsafeItemDataHandlersServer interface {
	mustEmbedUnimplementedItemDataHandlersServer()
}

func RegisterItemDataHandlersServer(s grpc.ServiceRegistrar, srv ItemDataHandlersServer) {
	// If the following call pancis, it indicates UnimplementedItemDataHandlersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ItemDataHandlers_ServiceDesc, srv)
}

func _ItemDataHandlers_PostItemData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostItemDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemDataHandlersServer).PostItemData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemDataHandlers_PostItemData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemDataHandlersServer).PostItemData(ctx, req.(*PostItemDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemDataHandlers_GetItemData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemDataHandlersServer).GetItemData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemDataHandlers_GetItemData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemDataHandlersServer).GetItemData(ctx, req.(*GetItemDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ItemDataHandlers_ServiceDesc is the grpc.ServiceDesc for ItemDataHandlers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ItemDataHandlers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server_grpc.ItemDataHandlers",
	HandlerType: (*ItemDataHandlersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostItemData",
			Handler:    _ItemDataHandlers_PostItemData_Handler,
		},
		{
			MethodName: "GetItemData",
			Handler:    _ItemDataHandlers_GetItemData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/handlers.proto",
}

const (
	MetaDataHandlers_GetMetaData_FullMethodName    = "/server_grpc.MetaDataHandlers/GetMetaData"
	MetaDataHandlers_DeleteMetaData_FullMethodName = "/server_grpc.MetaDataHandlers/DeleteMetaData"
)

// MetaDataHandlersClient is the client API for MetaDataHandlers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetaDataHandlersClient interface {
	GetMetaData(ctx context.Context, in *GetMetaDataRequest, opts ...grpc.CallOption) (*GetMetaDataResponse, error)
	DeleteMetaData(ctx context.Context, in *DeleteMetaDataRequest, opts ...grpc.CallOption) (*DeleteMetaDataResponse, error)
}

type metaDataHandlersClient struct {
	cc grpc.ClientConnInterface
}

func NewMetaDataHandlersClient(cc grpc.ClientConnInterface) MetaDataHandlersClient {
	return &metaDataHandlersClient{cc}
}

func (c *metaDataHandlersClient) GetMetaData(ctx context.Context, in *GetMetaDataRequest, opts ...grpc.CallOption) (*GetMetaDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetaDataResponse)
	err := c.cc.Invoke(ctx, MetaDataHandlers_GetMetaData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaDataHandlersClient) DeleteMetaData(ctx context.Context, in *DeleteMetaDataRequest, opts ...grpc.CallOption) (*DeleteMetaDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMetaDataResponse)
	err := c.cc.Invoke(ctx, MetaDataHandlers_DeleteMetaData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaDataHandlersServer is the server API for MetaDataHandlers service.
// All implementations must embed UnimplementedMetaDataHandlersServer
// for forward compatibility.
type MetaDataHandlersServer interface {
	GetMetaData(context.Context, *GetMetaDataRequest) (*GetMetaDataResponse, error)
	DeleteMetaData(context.Context, *DeleteMetaDataRequest) (*DeleteMetaDataResponse, error)
	mustEmbedUnimplementedMetaDataHandlersServer()
}

// UnimplementedMetaDataHandlersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetaDataHandlersServer struct{}

func (UnimplementedMetaDataHandlersServer) GetMetaData(context.Context, *GetMetaDataRequest) (*GetMetaDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetaData not implemented")
}
func (UnimplementedMetaDataHandlersServer) DeleteMetaData(context.Context, *DeleteMetaDataRequest) (*DeleteMetaDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMetaData not implemented")
}
func (UnimplementedMetaDataHandlersServer) mustEmbedUnimplementedMetaDataHandlersServer() {}
func (UnimplementedMetaDataHandlersServer) testEmbeddedByValue()                          {}

// UnsafeMetaDataHandlersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetaDataHandlersServer will
// result in compilation errors.
type UnsafeMetaDataHandlersServer interface {
	mustEmbedUnimplementedMetaDataHandlersServer()
}

func RegisterMetaDataHandlersServer(s grpc.ServiceRegistrar, srv MetaDataHandlersServer) {
	// If the following call pancis, it indicates UnimplementedMetaDataHandlersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetaDataHandlers_ServiceDesc, srv)
}

func _MetaDataHandlers_GetMetaData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetaDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaDataHandlersServer).GetMetaData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaDataHandlers_GetMetaData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaDataHandlersServer).GetMetaData(ctx, req.(*GetMetaDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaDataHandlers_DeleteMetaData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMetaDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaDataHandlersServer).DeleteMetaData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaDataHandlers_DeleteMetaData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaDataHandlersServer).DeleteMetaData(ctx, req.(*DeleteMetaDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetaDataHandlers_ServiceDesc is the grpc.ServiceDesc for MetaDataHandlers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetaDataHandlers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server_grpc.MetaDataHandlers",
	HandlerType: (*MetaDataHandlersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetaData",
			Handler:    _MetaDataHandlers_GetMetaData_Handler,
		},
		{
			MethodName: "DeleteMetaData",
			Handler:    _MetaDataHandlers_DeleteMetaData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/handlers.proto",
}
