// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/proto/handlers.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostUserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUserDataRequest) Reset() {
	*x = PostUserDataRequest{}
	mi := &file_internal_proto_handlers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUserDataRequest) ProtoMessage() {}

func (x *PostUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUserDataRequest.ProtoReflect.Descriptor instead.
func (*PostUserDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{0}
}

func (x *PostUserDataRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *PostUserDataRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PostUserDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // ошибка
	Jwt           string                 `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUserDataResponse) Reset() {
	*x = PostUserDataResponse{}
	mi := &file_internal_proto_handlers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUserDataResponse) ProtoMessage() {}

func (x *PostUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUserDataResponse.ProtoReflect.Descriptor instead.
func (*PostUserDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{1}
}

func (x *PostUserDataResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PostUserDataResponse) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

func (x *PostUserDataResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PostItemDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	DataId        string                 `protobuf:"bytes,2,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	MetaData      *MetaData              `protobuf:"bytes,3,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostItemDataRequest) Reset() {
	*x = PostItemDataRequest{}
	mi := &file_internal_proto_handlers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostItemDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostItemDataRequest) ProtoMessage() {}

func (x *PostItemDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostItemDataRequest.ProtoReflect.Descriptor instead.
func (*PostItemDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{2}
}

func (x *PostItemDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PostItemDataRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *PostItemDataRequest) GetMetaData() *MetaData {
	if x != nil {
		return x.MetaData
	}
	return nil
}

type PostItemDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataId        string                 `protobuf:"bytes,1,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	Created       string                 `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	Modified      string                 `protobuf:"bytes,3,opt,name=modified,proto3" json:"modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostItemDataResponse) Reset() {
	*x = PostItemDataResponse{}
	mi := &file_internal_proto_handlers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostItemDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostItemDataResponse) ProtoMessage() {}

func (x *PostItemDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostItemDataResponse.ProtoReflect.Descriptor instead.
func (*PostItemDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{3}
}

func (x *PostItemDataResponse) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *PostItemDataResponse) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *PostItemDataResponse) GetModified() string {
	if x != nil {
		return x.Modified
	}
	return ""
}

type GetItemDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataId        string                 `protobuf:"bytes,1,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemDataRequest) Reset() {
	*x = GetItemDataRequest{}
	mi := &file_internal_proto_handlers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemDataRequest) ProtoMessage() {}

func (x *GetItemDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemDataRequest.ProtoReflect.Descriptor instead.
func (*GetItemDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{4}
}

func (x *GetItemDataRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

type GetItemDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemDataResponse) Reset() {
	*x = GetItemDataResponse{}
	mi := &file_internal_proto_handlers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemDataResponse) ProtoMessage() {}

func (x *GetItemDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemDataResponse.ProtoReflect.Descriptor instead.
func (*GetItemDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{5}
}

func (x *GetItemDataResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type MetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DataType      string                 `protobuf:"bytes,4,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	DataId        string                 `protobuf:"bytes,5,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Created       string                 `protobuf:"bytes,7,opt,name=created,proto3" json:"created,omitempty"`
	Modified      string                 `protobuf:"bytes,8,opt,name=modified,proto3" json:"modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaData) Reset() {
	*x = MetaData{}
	mi := &file_internal_proto_handlers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaData) ProtoMessage() {}

func (x *MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaData.ProtoReflect.Descriptor instead.
func (*MetaData) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{6}
}

func (x *MetaData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetaData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MetaData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MetaData) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *MetaData) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *MetaData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MetaData) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *MetaData) GetModified() string {
	if x != nil {
		return x.Modified
	}
	return ""
}

type GetMetaDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetaDataRequest) Reset() {
	*x = GetMetaDataRequest{}
	mi := &file_internal_proto_handlers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetaDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetaDataRequest) ProtoMessage() {}

func (x *GetMetaDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetaDataRequest.ProtoReflect.Descriptor instead.
func (*GetMetaDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{7}
}

func (x *GetMetaDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetMetaDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MetaData            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetaDataResponse) Reset() {
	*x = GetMetaDataResponse{}
	mi := &file_internal_proto_handlers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetaDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetaDataResponse) ProtoMessage() {}

func (x *GetMetaDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetaDataResponse.ProtoReflect.Descriptor instead.
func (*GetMetaDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{8}
}

func (x *GetMetaDataResponse) GetItems() []*MetaData {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteMetaDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetadataId    string                 `protobuf:"bytes,1,opt,name=metadata_id,json=metadataId,proto3" json:"metadata_id,omitempty"`
	MetadataType  string                 `protobuf:"bytes,2,opt,name=metadata_type,json=metadataType,proto3" json:"metadata_type,omitempty"`
	DataId        string                 `protobuf:"bytes,3,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMetaDataRequest) Reset() {
	*x = DeleteMetaDataRequest{}
	mi := &file_internal_proto_handlers_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMetaDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMetaDataRequest) ProtoMessage() {}

func (x *DeleteMetaDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMetaDataRequest.ProtoReflect.Descriptor instead.
func (*DeleteMetaDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMetaDataRequest) GetMetadataId() string {
	if x != nil {
		return x.MetadataId
	}
	return ""
}

func (x *DeleteMetaDataRequest) GetMetadataType() string {
	if x != nil {
		return x.MetadataType
	}
	return ""
}

func (x *DeleteMetaDataRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

type DeleteMetaDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMetaDataResponse) Reset() {
	*x = DeleteMetaDataResponse{}
	mi := &file_internal_proto_handlers_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMetaDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMetaDataResponse) ProtoMessage() {}

func (x *DeleteMetaDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMetaDataResponse.ProtoReflect.Descriptor instead.
func (*DeleteMetaDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMetaDataResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_proto_handlers_proto protoreflect.FileDescriptor

const file_internal_proto_handlers_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/proto/handlers.proto\x12\vserver_grpc\"G\n" +
	"\x13PostUserDataRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"W\n" +
	"\x14PostUserDataResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x10\n" +
	"\x03jwt\x18\x02 \x01(\tR\x03jwt\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"v\n" +
	"\x13PostItemDataRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x17\n" +
	"\adata_id\x18\x02 \x01(\tR\x06dataId\x122\n" +
	"\tmeta_data\x18\x03 \x01(\v2\x15.server_grpc.MetaDataR\bmetaData\"e\n" +
	"\x14PostItemDataResponse\x12\x17\n" +
	"\adata_id\x18\x01 \x01(\tR\x06dataId\x12\x18\n" +
	"\acreated\x18\x02 \x01(\tR\acreated\x12\x1a\n" +
	"\bmodified\x18\x03 \x01(\tR\bmodified\"-\n" +
	"\x12GetItemDataRequest\x12\x17\n" +
	"\adata_id\x18\x01 \x01(\tR\x06dataId\")\n" +
	"\x13GetItemDataResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xd7\x01\n" +
	"\bMetaData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tdata_type\x18\x04 \x01(\tR\bdataType\x12\x17\n" +
	"\adata_id\x18\x05 \x01(\tR\x06dataId\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x12\x18\n" +
	"\acreated\x18\a \x01(\tR\acreated\x12\x1a\n" +
	"\bmodified\x18\b \x01(\tR\bmodified\"-\n" +
	"\x12GetMetaDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"B\n" +
	"\x13GetMetaDataResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.server_grpc.MetaDataR\x05items\"v\n" +
	"\x15DeleteMetaDataRequest\x12\x1f\n" +
	"\vmetadata_id\x18\x01 \x01(\tR\n" +
	"metadataId\x12#\n" +
	"\rmetadata_type\x18\x02 \x01(\tR\fmetadataType\x12\x17\n" +
	"\adata_id\x18\x03 \x01(\tR\x06dataId\".\n" +
	"\x16DeleteMetaDataResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2c\n" +
	"\fUserHandlers\x12S\n" +
	"\fPostUserData\x12 .server_grpc.PostUserDataRequest\x1a!.server_grpc.PostUserDataResponse2\xb9\x01\n" +
	"\x10ItemDataHandlers\x12S\n" +
	"\fPostItemData\x12 .server_grpc.PostItemDataRequest\x1a!.server_grpc.PostItemDataResponse\x12P\n" +
	"\vGetItemData\x12\x1f.server_grpc.GetItemDataRequest\x1a .server_grpc.GetItemDataResponse2\xbf\x01\n" +
	"\x10MetaDataHandlers\x12P\n" +
	"\vGetMetaData\x12\x1f.server_grpc.GetMetaDataRequest\x1a .server_grpc.GetMetaDataResponse\x12Y\n" +
	"\x0eDeleteMetaData\x12\".server_grpc.DeleteMetaDataRequest\x1a#.server_grpc.DeleteMetaDataResponseB\x13Z\x11internal/protobufb\x06proto3"

var (
	file_internal_proto_handlers_proto_rawDescOnce sync.Once
	file_internal_proto_handlers_proto_rawDescData []byte
)

func file_internal_proto_handlers_proto_rawDescGZIP() []byte {
	file_internal_proto_handlers_proto_rawDescOnce.Do(func() {
		file_internal_proto_handlers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_handlers_proto_rawDesc), len(file_internal_proto_handlers_proto_rawDesc)))
	})
	return file_internal_proto_handlers_proto_rawDescData
}

var file_internal_proto_handlers_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_proto_handlers_proto_goTypes = []any{
	(*PostUserDataRequest)(nil),    // 0: server_grpc.PostUserDataRequest
	(*PostUserDataResponse)(nil),   // 1: server_grpc.PostUserDataResponse
	(*PostItemDataRequest)(nil),    // 2: server_grpc.PostItemDataRequest
	(*PostItemDataResponse)(nil),   // 3: server_grpc.PostItemDataResponse
	(*GetItemDataRequest)(nil),     // 4: server_grpc.GetItemDataRequest
	(*GetItemDataResponse)(nil),    // 5: server_grpc.GetItemDataResponse
	(*MetaData)(nil),               // 6: server_grpc.MetaData
	(*GetMetaDataRequest)(nil),     // 7: server_grpc.GetMetaDataRequest
	(*GetMetaDataResponse)(nil),    // 8: server_grpc.GetMetaDataResponse
	(*DeleteMetaDataRequest)(nil),  // 9: server_grpc.DeleteMetaDataRequest
	(*DeleteMetaDataResponse)(nil), // 10: server_grpc.DeleteMetaDataResponse
}
var file_internal_proto_handlers_proto_depIdxs = []int32{
	6,  // 0: server_grpc.PostItemDataRequest.meta_data:type_name -> server_grpc.MetaData
	6,  // 1: server_grpc.GetMetaDataResponse.items:type_name -> server_grpc.MetaData
	0,  // 2: server_grpc.UserHandlers.PostUserData:input_type -> server_grpc.PostUserDataRequest
	2,  // 3: server_grpc.ItemDataHandlers.PostItemData:input_type -> server_grpc.PostItemDataRequest
	4,  // 4: server_grpc.ItemDataHandlers.GetItemData:input_type -> server_grpc.GetItemDataRequest
	7,  // 5: server_grpc.MetaDataHandlers.GetMetaData:input_type -> server_grpc.GetMetaDataRequest
	9,  // 6: server_grpc.MetaDataHandlers.DeleteMetaData:input_type -> server_grpc.DeleteMetaDataRequest
	1,  // 7: server_grpc.UserHandlers.PostUserData:output_type -> server_grpc.PostUserDataResponse
	3,  // 8: server_grpc.ItemDataHandlers.PostItemData:output_type -> server_grpc.PostItemDataResponse
	5,  // 9: server_grpc.ItemDataHandlers.GetItemData:output_type -> server_grpc.GetItemDataResponse
	8,  // 10: server_grpc.MetaDataHandlers.GetMetaData:output_type -> server_grpc.GetMetaDataResponse
	10, // 11: server_grpc.MetaDataHandlers.DeleteMetaData:output_type -> server_grpc.DeleteMetaDataResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_handlers_proto_init() }
func file_internal_proto_handlers_proto_init() {
	if File_internal_proto_handlers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_handlers_proto_rawDesc), len(file_internal_proto_handlers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_internal_proto_handlers_proto_goTypes,
		DependencyIndexes: file_internal_proto_handlers_proto_depIdxs,
		MessageInfos:      file_internal_proto_handlers_proto_msgTypes,
	}.Build()
	File_internal_proto_handlers_proto = out.File
	file_internal_proto_handlers_proto_goTypes = nil
	file_internal_proto_handlers_proto_depIdxs = nil
}
