// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/proto/handlers.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostUserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUserDataRequest) Reset() {
	*x = PostUserDataRequest{}
	mi := &file_internal_proto_handlers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUserDataRequest) ProtoMessage() {}

func (x *PostUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUserDataRequest.ProtoReflect.Descriptor instead.
func (*PostUserDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{0}
}

func (x *PostUserDataRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *PostUserDataRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PostUserDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // ошибка
	Jwt           string                 `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUserDataResponse) Reset() {
	*x = PostUserDataResponse{}
	mi := &file_internal_proto_handlers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUserDataResponse) ProtoMessage() {}

func (x *PostUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUserDataResponse.ProtoReflect.Descriptor instead.
func (*PostUserDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{1}
}

func (x *PostUserDataResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PostUserDataResponse) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

type PostTextDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	TextId        string                 `protobuf:"bytes,2,opt,name=text_id,json=textId,proto3" json:"text_id,omitempty"`
	MetaData      *MetaData              `protobuf:"bytes,3,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostTextDataRequest) Reset() {
	*x = PostTextDataRequest{}
	mi := &file_internal_proto_handlers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTextDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTextDataRequest) ProtoMessage() {}

func (x *PostTextDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTextDataRequest.ProtoReflect.Descriptor instead.
func (*PostTextDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{2}
}

func (x *PostTextDataRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PostTextDataRequest) GetTextId() string {
	if x != nil {
		return x.TextId
	}
	return ""
}

func (x *PostTextDataRequest) GetMetaData() *MetaData {
	if x != nil {
		return x.MetaData
	}
	return nil
}

type PostTextDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataId        string                 `protobuf:"bytes,1,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	Created       string                 `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	Modified      string                 `protobuf:"bytes,3,opt,name=modified,proto3" json:"modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostTextDataResponse) Reset() {
	*x = PostTextDataResponse{}
	mi := &file_internal_proto_handlers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTextDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTextDataResponse) ProtoMessage() {}

func (x *PostTextDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTextDataResponse.ProtoReflect.Descriptor instead.
func (*PostTextDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{3}
}

func (x *PostTextDataResponse) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *PostTextDataResponse) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *PostTextDataResponse) GetModified() string {
	if x != nil {
		return x.Modified
	}
	return ""
}

type GetTextDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TextId        string                 `protobuf:"bytes,1,opt,name=text_id,json=textId,proto3" json:"text_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTextDataRequest) Reset() {
	*x = GetTextDataRequest{}
	mi := &file_internal_proto_handlers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTextDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTextDataRequest) ProtoMessage() {}

func (x *GetTextDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTextDataRequest.ProtoReflect.Descriptor instead.
func (*GetTextDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{4}
}

func (x *GetTextDataRequest) GetTextId() string {
	if x != nil {
		return x.TextId
	}
	return ""
}

type GetTextDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTextDataResponse) Reset() {
	*x = GetTextDataResponse{}
	mi := &file_internal_proto_handlers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTextDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTextDataResponse) ProtoMessage() {}

func (x *GetTextDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTextDataResponse.ProtoReflect.Descriptor instead.
func (*GetTextDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{5}
}

func (x *GetTextDataResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PostBankCardDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNum       string                 `protobuf:"bytes,1,opt,name=card_num,json=cardNum,proto3" json:"card_num,omitempty"`
	Expiry        string                 `protobuf:"bytes,2,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Cvv           string                 `protobuf:"bytes,3,opt,name=cvv,proto3" json:"cvv,omitempty"`
	CardId        string                 `protobuf:"bytes,4,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	MetaData      *MetaData              `protobuf:"bytes,5,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostBankCardDataRequest) Reset() {
	*x = PostBankCardDataRequest{}
	mi := &file_internal_proto_handlers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBankCardDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBankCardDataRequest) ProtoMessage() {}

func (x *PostBankCardDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBankCardDataRequest.ProtoReflect.Descriptor instead.
func (*PostBankCardDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{6}
}

func (x *PostBankCardDataRequest) GetCardNum() string {
	if x != nil {
		return x.CardNum
	}
	return ""
}

func (x *PostBankCardDataRequest) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *PostBankCardDataRequest) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *PostBankCardDataRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *PostBankCardDataRequest) GetMetaData() *MetaData {
	if x != nil {
		return x.MetaData
	}
	return nil
}

type PostBankCardDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataId        string                 `protobuf:"bytes,1,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	Created       string                 `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	Modified      string                 `protobuf:"bytes,3,opt,name=modified,proto3" json:"modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostBankCardDataResponse) Reset() {
	*x = PostBankCardDataResponse{}
	mi := &file_internal_proto_handlers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBankCardDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBankCardDataResponse) ProtoMessage() {}

func (x *PostBankCardDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBankCardDataResponse.ProtoReflect.Descriptor instead.
func (*PostBankCardDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{7}
}

func (x *PostBankCardDataResponse) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *PostBankCardDataResponse) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *PostBankCardDataResponse) GetModified() string {
	if x != nil {
		return x.Modified
	}
	return ""
}

type GetBankCardDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBankCardDataRequest) Reset() {
	*x = GetBankCardDataRequest{}
	mi := &file_internal_proto_handlers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBankCardDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBankCardDataRequest) ProtoMessage() {}

func (x *GetBankCardDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBankCardDataRequest.ProtoReflect.Descriptor instead.
func (*GetBankCardDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{8}
}

func (x *GetBankCardDataRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type GetBankCardDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNum       string                 `protobuf:"bytes,1,opt,name=card_num,json=cardNum,proto3" json:"card_num,omitempty"`
	Expiry        string                 `protobuf:"bytes,2,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Cvv           string                 `protobuf:"bytes,3,opt,name=cvv,proto3" json:"cvv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBankCardDataResponse) Reset() {
	*x = GetBankCardDataResponse{}
	mi := &file_internal_proto_handlers_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBankCardDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBankCardDataResponse) ProtoMessage() {}

func (x *GetBankCardDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBankCardDataResponse.ProtoReflect.Descriptor instead.
func (*GetBankCardDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{9}
}

func (x *GetBankCardDataResponse) GetCardNum() string {
	if x != nil {
		return x.CardNum
	}
	return ""
}

func (x *GetBankCardDataResponse) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *GetBankCardDataResponse) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

type PostBinaryDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostBinaryDataRequest) Reset() {
	*x = PostBinaryDataRequest{}
	mi := &file_internal_proto_handlers_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBinaryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBinaryDataRequest) ProtoMessage() {}

func (x *PostBinaryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBinaryDataRequest.ProtoReflect.Descriptor instead.
func (*PostBinaryDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{10}
}

func (x *PostBinaryDataRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PostBinaryDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostBinaryDataResponse) Reset() {
	*x = PostBinaryDataResponse{}
	mi := &file_internal_proto_handlers_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBinaryDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBinaryDataResponse) ProtoMessage() {}

func (x *PostBinaryDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBinaryDataResponse.ProtoReflect.Descriptor instead.
func (*PostBinaryDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{11}
}

func (x *PostBinaryDataResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetBinaryDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBinaryDataRequest) Reset() {
	*x = GetBinaryDataRequest{}
	mi := &file_internal_proto_handlers_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBinaryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBinaryDataRequest) ProtoMessage() {}

func (x *GetBinaryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBinaryDataRequest.ProtoReflect.Descriptor instead.
func (*GetBinaryDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{12}
}

func (x *GetBinaryDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBinaryDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBinaryDataResponse) Reset() {
	*x = GetBinaryDataResponse{}
	mi := &file_internal_proto_handlers_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBinaryDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBinaryDataResponse) ProtoMessage() {}

func (x *GetBinaryDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBinaryDataResponse.ProtoReflect.Descriptor instead.
func (*GetBinaryDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{13}
}

func (x *GetBinaryDataResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type MetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DataType      string                 `protobuf:"bytes,4,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	DataId        string                 `protobuf:"bytes,5,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Created       string                 `protobuf:"bytes,7,opt,name=created,proto3" json:"created,omitempty"`
	Modified      string                 `protobuf:"bytes,8,opt,name=modified,proto3" json:"modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaData) Reset() {
	*x = MetaData{}
	mi := &file_internal_proto_handlers_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaData) ProtoMessage() {}

func (x *MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaData.ProtoReflect.Descriptor instead.
func (*MetaData) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{14}
}

func (x *MetaData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetaData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MetaData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MetaData) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *MetaData) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *MetaData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MetaData) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *MetaData) GetModified() string {
	if x != nil {
		return x.Modified
	}
	return ""
}

type GetMetaDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetaDataRequest) Reset() {
	*x = GetMetaDataRequest{}
	mi := &file_internal_proto_handlers_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetaDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetaDataRequest) ProtoMessage() {}

func (x *GetMetaDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetaDataRequest.ProtoReflect.Descriptor instead.
func (*GetMetaDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{15}
}

func (x *GetMetaDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetMetaDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MetaData            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetaDataResponse) Reset() {
	*x = GetMetaDataResponse{}
	mi := &file_internal_proto_handlers_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetaDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetaDataResponse) ProtoMessage() {}

func (x *GetMetaDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_handlers_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetaDataResponse.ProtoReflect.Descriptor instead.
func (*GetMetaDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_handlers_proto_rawDescGZIP(), []int{16}
}

func (x *GetMetaDataResponse) GetItems() []*MetaData {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_internal_proto_handlers_proto protoreflect.FileDescriptor

const file_internal_proto_handlers_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/proto/handlers.proto\x12\vserver_grpc\"G\n" +
	"\x13PostUserDataRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\">\n" +
	"\x14PostUserDataResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x10\n" +
	"\x03jwt\x18\x02 \x01(\tR\x03jwt\"v\n" +
	"\x13PostTextDataRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x17\n" +
	"\atext_id\x18\x02 \x01(\tR\x06textId\x122\n" +
	"\tmeta_data\x18\x03 \x01(\v2\x15.server_grpc.MetaDataR\bmetaData\"e\n" +
	"\x14PostTextDataResponse\x12\x17\n" +
	"\adata_id\x18\x01 \x01(\tR\x06dataId\x12\x18\n" +
	"\acreated\x18\x02 \x01(\tR\acreated\x12\x1a\n" +
	"\bmodified\x18\x03 \x01(\tR\bmodified\"-\n" +
	"\x12GetTextDataRequest\x12\x17\n" +
	"\atext_id\x18\x01 \x01(\tR\x06textId\")\n" +
	"\x13GetTextDataResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xab\x01\n" +
	"\x17PostBankCardDataRequest\x12\x19\n" +
	"\bcard_num\x18\x01 \x01(\tR\acardNum\x12\x16\n" +
	"\x06expiry\x18\x02 \x01(\tR\x06expiry\x12\x10\n" +
	"\x03cvv\x18\x03 \x01(\tR\x03cvv\x12\x17\n" +
	"\acard_id\x18\x04 \x01(\tR\x06cardId\x122\n" +
	"\tmeta_data\x18\x05 \x01(\v2\x15.server_grpc.MetaDataR\bmetaData\"i\n" +
	"\x18PostBankCardDataResponse\x12\x17\n" +
	"\adata_id\x18\x01 \x01(\tR\x06dataId\x12\x18\n" +
	"\acreated\x18\x02 \x01(\tR\acreated\x12\x1a\n" +
	"\bmodified\x18\x03 \x01(\tR\bmodified\"1\n" +
	"\x16GetBankCardDataRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\"^\n" +
	"\x17GetBankCardDataResponse\x12\x19\n" +
	"\bcard_num\x18\x01 \x01(\tR\acardNum\x12\x16\n" +
	"\x06expiry\x18\x02 \x01(\tR\x06expiry\x12\x10\n" +
	"\x03cvv\x18\x03 \x01(\tR\x03cvv\"+\n" +
	"\x15PostBinaryDataRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\".\n" +
	"\x16PostBinaryDataResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"&\n" +
	"\x14GetBinaryDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x15GetBinaryDataResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xd7\x01\n" +
	"\bMetaData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tdata_type\x18\x04 \x01(\tR\bdataType\x12\x17\n" +
	"\adata_id\x18\x05 \x01(\tR\x06dataId\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x12\x18\n" +
	"\acreated\x18\a \x01(\tR\acreated\x12\x1a\n" +
	"\bmodified\x18\b \x01(\tR\bmodified\"-\n" +
	"\x12GetMetaDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"B\n" +
	"\x13GetMetaDataResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.server_grpc.MetaDataR\x05items2c\n" +
	"\fUserHandlers\x12S\n" +
	"\fPostUserData\x12 .server_grpc.PostUserDataRequest\x1a!.server_grpc.PostUserDataResponse2\xb5\x01\n" +
	"\fTextHandlers\x12S\n" +
	"\fPostTextData\x12 .server_grpc.PostTextDataRequest\x1a!.server_grpc.PostTextDataResponse\x12P\n" +
	"\vGetTextData\x12\x1f.server_grpc.GetTextDataRequest\x1a .server_grpc.GetTextDataResponse2\xd1\x01\n" +
	"\x10BankCardHandlers\x12_\n" +
	"\x10PostBankCardData\x12$.server_grpc.PostBankCardDataRequest\x1a%.server_grpc.PostBankCardDataResponse\x12\\\n" +
	"\x0fGetBankCardData\x12#.server_grpc.GetBankCardDataRequest\x1a$.server_grpc.GetBankCardDataResponse2d\n" +
	"\x10MetaDataHandlers\x12P\n" +
	"\vGetMetaData\x12\x1f.server_grpc.GetMetaDataRequest\x1a .server_grpc.GetMetaDataResponseB\x13Z\x11internal/protobufb\x06proto3"

var (
	file_internal_proto_handlers_proto_rawDescOnce sync.Once
	file_internal_proto_handlers_proto_rawDescData []byte
)

func file_internal_proto_handlers_proto_rawDescGZIP() []byte {
	file_internal_proto_handlers_proto_rawDescOnce.Do(func() {
		file_internal_proto_handlers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_handlers_proto_rawDesc), len(file_internal_proto_handlers_proto_rawDesc)))
	})
	return file_internal_proto_handlers_proto_rawDescData
}

var file_internal_proto_handlers_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_proto_handlers_proto_goTypes = []any{
	(*PostUserDataRequest)(nil),      // 0: server_grpc.PostUserDataRequest
	(*PostUserDataResponse)(nil),     // 1: server_grpc.PostUserDataResponse
	(*PostTextDataRequest)(nil),      // 2: server_grpc.PostTextDataRequest
	(*PostTextDataResponse)(nil),     // 3: server_grpc.PostTextDataResponse
	(*GetTextDataRequest)(nil),       // 4: server_grpc.GetTextDataRequest
	(*GetTextDataResponse)(nil),      // 5: server_grpc.GetTextDataResponse
	(*PostBankCardDataRequest)(nil),  // 6: server_grpc.PostBankCardDataRequest
	(*PostBankCardDataResponse)(nil), // 7: server_grpc.PostBankCardDataResponse
	(*GetBankCardDataRequest)(nil),   // 8: server_grpc.GetBankCardDataRequest
	(*GetBankCardDataResponse)(nil),  // 9: server_grpc.GetBankCardDataResponse
	(*PostBinaryDataRequest)(nil),    // 10: server_grpc.PostBinaryDataRequest
	(*PostBinaryDataResponse)(nil),   // 11: server_grpc.PostBinaryDataResponse
	(*GetBinaryDataRequest)(nil),     // 12: server_grpc.GetBinaryDataRequest
	(*GetBinaryDataResponse)(nil),    // 13: server_grpc.GetBinaryDataResponse
	(*MetaData)(nil),                 // 14: server_grpc.MetaData
	(*GetMetaDataRequest)(nil),       // 15: server_grpc.GetMetaDataRequest
	(*GetMetaDataResponse)(nil),      // 16: server_grpc.GetMetaDataResponse
}
var file_internal_proto_handlers_proto_depIdxs = []int32{
	14, // 0: server_grpc.PostTextDataRequest.meta_data:type_name -> server_grpc.MetaData
	14, // 1: server_grpc.PostBankCardDataRequest.meta_data:type_name -> server_grpc.MetaData
	14, // 2: server_grpc.GetMetaDataResponse.items:type_name -> server_grpc.MetaData
	0,  // 3: server_grpc.UserHandlers.PostUserData:input_type -> server_grpc.PostUserDataRequest
	2,  // 4: server_grpc.TextHandlers.PostTextData:input_type -> server_grpc.PostTextDataRequest
	4,  // 5: server_grpc.TextHandlers.GetTextData:input_type -> server_grpc.GetTextDataRequest
	6,  // 6: server_grpc.BankCardHandlers.PostBankCardData:input_type -> server_grpc.PostBankCardDataRequest
	8,  // 7: server_grpc.BankCardHandlers.GetBankCardData:input_type -> server_grpc.GetBankCardDataRequest
	15, // 8: server_grpc.MetaDataHandlers.GetMetaData:input_type -> server_grpc.GetMetaDataRequest
	1,  // 9: server_grpc.UserHandlers.PostUserData:output_type -> server_grpc.PostUserDataResponse
	3,  // 10: server_grpc.TextHandlers.PostTextData:output_type -> server_grpc.PostTextDataResponse
	5,  // 11: server_grpc.TextHandlers.GetTextData:output_type -> server_grpc.GetTextDataResponse
	7,  // 12: server_grpc.BankCardHandlers.PostBankCardData:output_type -> server_grpc.PostBankCardDataResponse
	9,  // 13: server_grpc.BankCardHandlers.GetBankCardData:output_type -> server_grpc.GetBankCardDataResponse
	16, // 14: server_grpc.MetaDataHandlers.GetMetaData:output_type -> server_grpc.GetMetaDataResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_proto_handlers_proto_init() }
func file_internal_proto_handlers_proto_init() {
	if File_internal_proto_handlers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_handlers_proto_rawDesc), len(file_internal_proto_handlers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_internal_proto_handlers_proto_goTypes,
		DependencyIndexes: file_internal_proto_handlers_proto_depIdxs,
		MessageInfos:      file_internal_proto_handlers_proto_msgTypes,
	}.Build()
	File_internal_proto_handlers_proto = out.File
	file_internal_proto_handlers_proto_goTypes = nil
	file_internal_proto_handlers_proto_depIdxs = nil
}
